### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Vazirified** [Vazirified/priorg#1]
PRIORG is a kind of fork from ILS idea, but since ILS implementations were all personal "quick and dirty" applications of the idea of reaching balance through a personal task manager, writing a new set of features and reflecting them in the project description and road map seems appropriate.

**Comment by Vazirified** [comment]
Since a user may choose to use (or not to use) any of the features/functionalities or extensions, a modular approach seems to be logical: each feature should be independent while respecting an overall interface and design language, storing data in a manner that is accessible by other modules and exposing an API accessible for other extensions.

**Comment by Vazirified** [comment]
In order to avoid reinventing the wheel, I believe that PRIORG must use existing protocols, objects and servers such as iCalendar (VTODO), CalDAV and EteSync or NextCloud. This way, prioritized tasks [assignments in PRIORG vocabulary] modified from the latest cycle of PRIORG run can be viewed or modified by other applications.

**Comment by Vazirified** [comment]
In order to make PRIORG able to work offline, a local copy of CalDAV collections should be created, modified and prioritized and finally synchronized with the remote copy. This makes the PRIORG input/output as straightforward as reading/writing .ics files.

**Comment by jaysi** [comment]
> In order to avoid reinventing the wheel, I believe that PRIORG must use existing protocols, objects and servers such as iCalendar (VTODO), CalDAV and EteSync or NextCloud. This way, prioritized tasks [assignments in PRIORG vocabulary] modified from the latest cycle of PRIORG run can be viewed or modified by other applications.



> In order to avoid reinventing the wheel, I believe that PRIORG must use existing protocols, objects and servers such as iCalendar (VTODO), CalDAV and EteSync or NextCloud. This way, prioritized tasks [assignments in PRIORG vocabulary] modified from the latest cycle of PRIORG run can be viewed or modified by other applications.

However, sometimes it takes a huge effort to understand other protocols, makes me think twice about reinventing the wheel!

**Comment by jaysi** [comment]
> In order to make PRIORG able to work offline, a local copy of CalDAV collections should be created, modified and prioritized and finally synchronized with the remote copy. This makes the PRIORG input/output as straightforward as reading/writing .ics files.

In a real world, It's a pain in the ...

**Comment by Vazirified** [comment]
Any idea on how to store a complex todo list in a relatively human readable format and staying compatible with the majority of other people's tools for calendaring without using iCalendar @jaysi?!
I'm afraid I won't have any other way... at least not at the start.

**Comment by Vazirified** [comment]
Since I do not have any other idea on how to proceed, I will stick to the .ics format.
At least in the first version, PRIORG will **create/sync a local collections of ICS files from a remote CalDAV server**, edits the files and synchronizes back to the server.
As many applications discard or do not sync X prefixed properties in .ics files, PRIORG will not store any information in custom properties and use a human readable method with **MarkDown to store and read/parse the required additional data from ILS in VTODO items' descriptions** and may have to create a couple of **additional VCALENDAR entries to store data** that are independent from the tasks.
The **results of prioritizing tasks will be stored as the priority number** of the VCALENDAR items, so that other applications can use the results with their priority sorted views.
Other features and probable future data-structures will be discussed after the release of an initial working command-line/TUI version that includes **synchronization, priority evaluation, editor and viewer modules**.
